spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false

  jpa:
    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
